package org.scajadoc.util

import extractor.TypeExtractor
import tools.nsc.doc.model.DocTemplateEntity

/**
 * Utility class which extracts Java specific information from entities
 * generated by the ModelFactory.
 *
 * @author Filip Rogaczewski
 */
object javaExtractor {

   val typeExtractor = new TypeExtractor

   def extractTypeInfo(info : DocTemplateEntity) = typeExtractor.extract(info)

}