package org.scajadoc.extractor

import tools.nsc.doc.model._

/**
 * Utility class which extracts Java specific information from entities
 * generated by the ModelFactory.
 *
 * @author Filip Rogaczewski
 */
object javaExtractor {

   private final val fieldExtractor = new FieldExtractor

   private final val methodExtractor = new MethodExtractor

   private final val typeExtractor = new TypeExtractor

   def extract(entity : MemberEntity) : Option[Extract] = {
      entity match {
         case v : Val => fieldExtractor.extract(v)
         case m : NonTemplateMemberEntity => methodExtractor.extract(m)
         case d : DocTemplateEntity => typeExtractor.extract(d)
         case _ => None
      }
   }

}